In [1]:
#Install yfinance to download stock information 
!pip install yfinance

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.12/site-packages (1.6.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.15 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (0.16.0)
Requirement already satisfied: lxml>=4.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (5.2.1)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (1.26.4)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (2.2.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (4.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (3.10.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (3.20.3)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (2024.1)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (2.32.2)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (17.0.1)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.2.2)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.12/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)

In [3]:
#Import some libraries for this download
from pathlib import Path
import pandas as pd
import yfinance as yf

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("Libraries imported")

Libraries imported

In [5]:
#Set time frame (Sept 1, 2016 - Sept 1, 2026)

START_DATE = '2016-09-01' #start date is inclusive 
END_DATE = '2026-09-02' #end date is exclusive

In [7]:
#Locate our project folder 

current_dir = Path.cwd()

if current_dir.name == 'notebooks':
    project_root = current_dir.parent
else:
    project_root = current_dir
raw_data_dir = project_root / "data" / "raw"

#Confirmation of folders' existence 
print("Project folder:", project_root)
print("Raw data folder:", raw_data_dir)
print("Folder exists?", raw_data_dir.exists())

Project folder: /Users/nghitran/CapSTOKED
Raw data folder: /Users/nghitran/CapSTOKED/data/raw
Folder exists? True

In [9]:
#50 company ticker universe 

tickers = [ 
    #Technology 
    "AAPL","MSFT","NVDA","AVGO","AMD","ORCL","CSCO","CRM","ADBE","INTC",
    #Consumer Staples 
    "WMT","COST","KO","PG",
    #Health Care 
    "LLY","JNJ","UNH","ABBV","PFE",
    #Energy           
    "XOM","CVX","COP",
    #Financials        
    "JPM","BAC","GS","V","BLK",
    #Utilities         
    "NEE","DUK","SO",
    #Consumer Disc.   
    "AMZN","TSLA","HD","MCD","NKE",
    #Materials         
    "LIN","SHW","APD",
    #Industrials    
    "CAT","GE","HON","RTX","UPS",
    #Real Estate      
    "PLD","AMT","O",
    #Communication   
    "GOOGL","META","NFLX","DIS",
]

#check quantity
print("Number of companies:", len(tickers))

Number of companies: 50

In [13]:
universe_data = yf.download( tickers=tickers, start= START_DATE, end= END_DATE, 
                           interval="1d", auto_adjust=False, group_by="ticker",
                           actions=False, progress=True, threads=True, timeout=30)

print("Download complete")

print("50-company universe shape:", universe_data.shape)
display(universe_data.head())

[*********************100%***********************]  50 of 50 completed

Download complete
50-company universe shape: (2513, 300)

Ticker        NFLX                                                     GS                                      \
Price         Open    High    Low   Close Adj Close    Volume        Open        High         Low       Close
Date
2016-09-01   9.781   9.798  9.692   9.738     9.738  41486000  170.000000  170.070007  166.660004  168.509995
2016-09-02   9.790   9.818  9.701   9.738     9.738  42472000  168.520004  169.740005  167.899994  169.179993
2016-09-06   9.776  10.032  9.765  10.009    10.009  90361000  168.720001  169.789993  167.470001  169.330002
2016-09-07  10.011  10.019  9.842   9.915     9.915  64685000  168.699997  170.210007  168.649994  169.669998
2016-09-08   9.923  10.005  9.882   9.966     9.966  52012000  169.350006  171.880005  168.710007  171.660004

Ticker                                 SHW                                                             COST  \
Price        Adj Close   Volume       Open       High        Low      Close  Adj Close   Volume        Open
Date
2016-09-01  137.027283  2843300  94.456665  95.423332  94.233330  95.089996  86.788406  3056400  159.000000
2016-09-02  137.572113  1747500  95.183334  95.786667  94.876663  95.476669  87.141342  1274100  156.809998
2016-09-06  137.694153  2034900  95.793335  95.793335  94.696671  95.043335  86.745842  1110900  158.130005
2016-09-07  137.970627  1584300  94.863335  95.699997  94.313332  95.496666  87.159584  2036700  157.639999
2016-09-08  139.588760  3031600  95.063332  95.363335  94.306664  94.449997  86.204330  1805400  155.190002

Ticker                                                                      APD                                      \
Price             High         Low       Close   Adj Close   Volume        Open        High         Low       Close
Date
2016-09-01  159.000000  155.539993  156.210007  131.961014  6038500  144.431076  144.819611  143.894547  144.588348
2016-09-02  159.279999  156.800003  157.979996  133.456284  2679000  145.235886  145.568924  144.616089  145.319153
2016-09-06  158.149994  156.020004  158.059998  133.523865  2716900  145.568924  146.012955  144.653091  145.605927
2016-09-07  157.869995  155.399994  155.639999  131.479492  2984100  144.976868  145.809433  144.625351  145.605927
2016-09-08  155.490005  152.940002  153.470001  129.646393  2993100  145.642929  145.874191  144.144318  144.209061

Ticker                                 DUK                                                             JPM             \
Price        Adj Close   Volume       Open       High        Low      Close  Adj Close   Volume       Open       High
Date
2016-09-01  112.451523  1408759  79.660004  79.800003  79.129997  79.330002  52.865273  2428600  67.639999  67.720001
2016-09-02  113.019905  1143806  79.330002  80.279999  79.220001  80.239998  53.471699  2767600  67.400002  67.580002
2016-09-06  113.242935  1272229  80.550003  81.230003  80.239998  80.940002  53.938175  2775900  67.500000  67.550003
2016-09-07  113.242935   759511  81.260002  81.260002  80.379997  80.540001  53.671612  2259600  67.160004  67.589996
2016-09-08  112.156540  1287471  80.440002  81.010002  80.269997  80.809998  53.851532  2047100  67.220001  67.680000

Ticker                                                       XOM                                                       \
Price             Low      Close  Adj Close    Volume       Open       High        Low      Close  Adj Close   Volume
Date
2016-09-01  66.650002  67.209999  51.422554  12226500  86.720001  86.839996  86.089996  86.839996  56.377445  8434700
2016-09-02  66.980003  67.489998  51.636780  13720700  87.419998  87.580002  86.930000  87.419998  56.753979  7099600
2016-09-06  66.709999  67.440002  51.598530  16649400  87.839996  88.639999  87.660004  88.570000  57.500576  9851200
2016-09-07  66.959999  67.160004  51.384296  10070400  88.650002  88.669998  87.970001  88.239998  57.286335  7470400
2016-09-08  67.000000  67.250000  51.453152  12253000  88.550003  89.370003  88.040001  89.050003  57.812210  9579500

Ticker            COP                                                              CAT                        \
Price            Open       High        Low      Close  Adj Close    Volume       Open       High        Low
Date
2016-09-01  40.900002  41.099998  40.130001  40.599998  29.801531   7536600  81.589996  82.000000  80.570000
2016-09-02  41.150002  41.310001  40.820000  40.919998  30.036427   5606700  82.190002  82.370003  81.470001
2016-09-06  41.040001  41.230000  40.610001  41.000000  30.095163   6654500  82.010002  82.230003  81.480003
2016-09-07  41.220001  41.500000  41.020000  41.480000  30.447481   6368800  82.500000  83.730003  82.410004
2016-09-08  41.919998  43.340000  41.669998  43.279999  31.768732  10714900  83.500000  83.959999  83.080002

Ticker                                           PFE                                                              CRM  \
Price           Close  Adj Close   Volume       Open       High        Low      Close  Adj Close    Volume       Open
Date
2016-09-01  81.449997  65.405792  4102200  32.950665  33.149906  32.836811  32.903225  20.889240  16780945  75.449997
2016-09-02  81.690002  65.598495  2449400  32.998100  33.055027  32.836811  32.988613  20.943449  15215333  76.000000
2016-09-06  82.080002  65.911697  3071000  33.092979  33.197342  32.969639  32.988613  20.943449  17882059  74.930000
2016-09-07  83.720001  67.228653  3996700  32.941177  33.102467  32.903225  33.055027  20.985609  15615537  75.070000
2016-09-08  83.540001  67.084076  3400500  32.931690  33.026566  32.846298  32.941177  20.913340  19216212  75.000000

Ticker                                                                    GE                                      \
Price            High        Low      Close  Adj Close    Volume        Open        High         Low       Close
Date
2016-09-01  76.550003  74.059998  75.910004  74.488014  27418500  149.284424  149.955368  148.373856  149.524048
2016-09-02  76.470001  74.650002  75.099998  73.693184   8153000  149.763672  150.722153  149.667816  149.955368
2016-09-06  75.620003  74.550003  75.419998  74.007179   5146000  150.051208  150.194992  147.607071  148.805176
2016-09-07  75.610001  74.580002  75.010002  73.604874   5566800  148.517639  148.853104  147.607071  148.853104
2016-09-08  75.019997  74.370003  74.879997  73.477287   5122200  148.565552  148.805176  148.086319  148.757263

Ticker                                TSLA                                                              INTC  \
Price        Adj Close   Volume       Open       High        Low      Close  Adj Close     Volume       Open
Date
2016-09-01  133.629257  8608480  13.934000  14.073333  13.366667  13.384667  13.384667  119146500  35.990002
2016-09-02  134.014771  4341736  13.488667  13.546667  13.080000  13.185333  13.185333   89661000  36.209999
2016-09-06  132.986816  8545902  13.268000  13.550000  13.266667  13.522000  13.522000   65859000  36.380001
2016-09-07  133.029694  5689568  13.700000  13.766667  13.380667  13.447333  13.447333   54613500  36.650002
2016-09-08  132.943970  6313322  13.303333  13.326000  13.090667  13.157333  13.157333   50668500  36.349998

Ticker                                                                   SO                                   \
Price            High        Low      Close  Adj Close    Volume       Open       High        Low      Close
Date
2016-09-01  36.040001  35.580002  36.020000  29.185301  18925800  51.240002  51.369999  51.009998  51.180000
2016-09-02  36.330002  35.950001  36.080002  29.233910  16726700  51.200001  51.849998  51.150002  51.799999
2016-09-06  36.599998  36.169998  36.570000  29.630947  22337800  51.910000  52.450001  51.830002  52.130001
2016-09-07  36.650002  36.380001  36.459999  29.541807  18495600  52.160000  52.340000  51.939999  52.220001
2016-09-08  36.590000  36.119999  36.439999  29.525604  20356500  52.259998  52.509998  52.080002  52.470001

Ticker                                 CVX                                                              GOOGL  \
Price       Adj Close   Volume        Open        High         Low       Close  Adj Close   Volume       Open
Date
2016-09-01  33.926041  3613600  100.349998  100.580002   99.470001  100.209999  65.726379  6045000  39.598999
2016-09-02  34.337029  3869300  100.889999  101.459999  100.260002  100.930000  66.198616  4676600  39.763500
2016-09-06  34.555794  5491400  101.209999  102.610001  100.970001  102.430000  67.182434  5429000  39.919498
2016-09-07  34.615433  3564500  102.750000  103.050003  102.239998  102.879997  67.477570  5284300  40.396500
2016-09-08  34.781158  4375900  103.339996  104.349998  102.470001  104.120003  68.290871  5788800  40.261002

Ticker                                                                   MCD                                      \
Price            High        Low      Close  Adj Close    Volume        Open        High         Low       Close
Date
2016-09-01  39.644501  39.316502  39.570000  39.197010  26070000  115.510002  115.809998  114.860001  115.400002
2016-09-02  39.855000  39.662998  39.843498  39.467937  26998000  115.930000  116.110001  115.699997  115.830002
2016-09-06  40.544498  39.771500  40.401001  40.020180  39790000  117.089996  119.239998  116.910004  117.250000
2016-09-07  40.529999  40.186001  40.399502  40.018696  22906000  117.269997  117.489998  116.440002  116.919998
2016-09-08  40.421001  40.050499  40.141998  39.763622  23554000  116.820000  117.110001  116.040001  116.169998

Ticker                           AMD                                              ADBE                          \
Price       Adj Close   Volume  Open  High   Low Close Adj Close    Volume        Open        High         Low
Date
2016-09-01  90.751747  3966600  7.18  7.44  7.09  7.35      7.35  22284600  102.230003  102.970001  101.809998
2016-09-02  91.089890  3410100  7.49  7.64  7.38  7.51      7.51  18538400  103.489998  104.160004  102.949997
2016-09-06  92.206573  6337900  7.56  7.60  7.25  7.34      7.34  24994600  103.330002  103.739998  103.089996
2016-09-07  91.947098  2647700  7.05  7.07  6.78  6.84      6.84  57721900  103.470001  103.510002  102.580002
2016-09-08  91.357300  3085600  6.64  6.65  6.15  6.23      6.23  90814700  102.769997  102.970001  101.620003

Ticker                                              LIN                                                           \
Price            Close   Adj Close   Volume        Open        High         Low       Close   Adj Close   Volume
Date
2016-09-01  102.900002  102.900002  2006600  122.269997  123.000000  121.940002  122.849998  103.485001  1224300
2016-09-02  103.570000  103.570000  1719300  123.040001  123.669998  122.900002  123.440002  103.982002   489600
2016-09-06  103.500000  103.500000  1585100  122.800003  123.360001  121.820000  122.160004  103.532829   787200
2016-09-07  103.000000  103.000000  1386500  121.860001  122.519997  121.400002  122.239998  103.600616   731300
2016-09-08  101.879997  101.879997  2110600  122.269997  122.419998  120.389999  120.570000  102.185287  1032100

Ticker             PG                                                              WMT                        \
Price            Open       High        Low      Close  Adj Close    Volume       Open       High        Low
Date
2016-09-01  87.360001  88.309998  86.980003  88.309998  67.253822  29793300  23.856667  24.286667  23.803333
2016-09-02  88.480003  88.870003  88.040001  88.199997  67.170052  17470400  24.330000  24.396667  24.139999
2016-09-06  88.250000  88.639999  87.879997  88.639999  67.505127  14472100  24.253332  24.360001  24.066668
2016-09-07  88.309998  88.410004  87.709999  87.949997  66.979652  17556400  24.333332  24.350000  24.003332
2016-09-08  87.949997  88.180000  87.629997  87.779999  66.850182  23465700  23.963333  24.106667  23.903334

Ticker                                             HON                                                          \
Price           Close  Adj Close    Volume        Open        High         Low       Close  Adj Close   Volume
Date
2016-09-01  24.280001  20.545326  35284200  109.692810  110.050911  108.505417  109.438370  89.133720  3043471
2016-09-02  24.166668  20.449432  24248700  109.560875  110.201698  109.136810  109.683388  89.333275  2625592
2016-09-06  24.333332  20.590456  28712700  109.739929  109.871864  108.382904  109.042572  88.811348  2328365
2016-09-07  24.020000  20.325325  28854900  108.863518  109.061417  107.176659  107.657272  87.683067  3625084
2016-09-08  23.943333  20.260441  28983600  107.431107  107.930565  106.988182  107.261475  87.360703  2869443

Ticker            PLD                                                            ORCL                        \
Price            Open       High        Low      Close  Adj Close   Volume       Open       High        Low
Date
2016-09-01  53.139999  53.270000  52.580002  53.020000  39.611526  1900000  40.980000  41.259998  40.779999
2016-09-02  53.330002  54.560001  53.240002  53.980000  40.328739  2390900  41.259998  41.419998  41.029999
2016-09-06  54.259998  54.509998  53.799999  54.130001  40.440811  2350800  41.369999  41.369999  41.070000
2016-09-07  53.950001  54.560001  53.770000  54.560001  40.762070  1555700  41.139999  41.310001  40.950001
2016-09-08  54.310001  54.439999  53.840000  54.040001  40.373569  4185000  40.930000  41.000000  40.599998

Ticker                                            META                                                            \
Price           Close  Adj Close    Volume        Open        High         Low       Close   Adj Close    Volume
Date
2016-09-01  41.160000  35.320938  10652500  126.379997  126.629997  125.599998  126.169998  124.973045  13536100
2016-09-02  41.250000  35.398174   9020200  126.849998  126.860001  126.000000  126.510002  125.309822  12118800
2016-09-06  41.250000  35.398174   8308300  126.669998  129.940002  126.470001  129.729996  128.499268  26278400
2016-09-07  41.250000  35.398174  10415300  130.039993  131.979996  129.949997  131.050003  129.806763  27990800
2016-09-08  40.720001  34.943359  16732100  130.919998  131.080002  129.809998  130.270004  129.034149  15676600

Ticker              HD                                                                CSCO                        \
Price             Open        High         Low       Close   Adj Close   Volume       Open       High        Low
Date
2016-09-01  134.479996  135.059998  133.660004  134.229996  105.179733  3851800  31.420000  31.639999  31.260000
2016-09-02  134.770004  135.880005  134.550003  135.149994  105.900612  3402600  31.650000  31.950001  31.650000
2016-09-06  134.960007  135.720001  133.880005  134.100006  105.077850  4220400  31.930000  31.940001  31.700001
2016-09-07  133.300003  133.869995  132.160004  132.789993  104.051346  4676000  31.790001  31.930000  31.750000
2016-09-08  131.550003  132.940002  131.119995  131.259995  102.852470  5019600  31.719999  31.750000  31.420000

Ticker                                           ABBV                                                             DIS  \
Price           Close  Adj Close    Volume       Open       High        Low      Close  Adj Close   Volume       Open
Date
2016-09-01  31.580000  23.376692  15980500  64.099998  64.139999  63.610001  64.029999  42.474865  5126700  94.730003
2016-09-02  31.830000  23.561749  18156500  64.370003  64.480003  63.869999  64.120003  42.534565  4100800  94.750000
2016-09-06  31.870001  23.591368  17656500  64.699997  64.900002  64.050003  64.610001  42.859619  6286300  94.529999
2016-09-07  31.790001  23.532143  14050500  64.370003  65.139999  64.290001  64.970001  43.098427  5714300  93.980003
2016-09-08  31.469999  23.295261  19913700  63.959999  64.150002  63.439999  64.059998  42.494766  8238800  93.489998

Ticker                                                                 NKE                                   \
Price            High        Low      Close  Adj Close   Volume       Open       High        Low      Close
Date
2016-09-01  94.870003  93.910004  94.260002  86.848587  6274200  57.669998  58.549999  57.529999  58.540001
2016-09-02  94.959999  94.129997  94.419998  86.996010  5382000  58.630001  59.180000  57.990002  58.020000
2016-09-06  94.529999  93.349998  93.800003  86.424751  8463500  58.250000  58.380001  57.209999  57.410000
2016-09-07  94.029999  93.330002  93.709999  86.341820  6281500  57.480000  57.779999  57.009998  57.720001
2016-09-08  94.209999  92.930000  94.089996  86.691933  7438100  56.880001  57.270000  56.110001  56.169998

Ticker                              NVDA                                                       AVGO             \
Price       Adj Close    Volume     Open     High      Low    Close Adj Close     Volume       Open       High
Date
2016-09-01  50.616154   8225000  1.53475  1.58450  1.53350  1.57875  1.549249  428492000  17.688000  17.767000
2016-09-02  50.166534   6933100  1.58200  1.58375  1.54550  1.56325  1.534039  323148000  17.700001  17.733999
2016-09-06  49.639111   9771800  1.56875  1.57800  1.56075  1.57800  1.548513  306812000  17.362000  17.400000
2016-09-07  49.907139   7536100  1.57300  1.58075  1.54575  1.55475  1.525697  397988000  17.142000  17.200001
2016-09-08  48.566948  12741900  1.55325  1.56850  1.53550  1.56600  1.536738  315808000  16.839001  16.882999

Ticker                                                       RTX                                                       \
Price             Low      Close  Adj Close    Volume       Open       High        Low      Close  Adj Close   Volume
Date
2016-09-01  17.482000  17.709000  13.550704  39128000  67.174324  67.319069  66.519821  67.161736  53.478371  5134854
2016-09-02  16.879999  17.311001  13.246165  80668000  67.457520  67.791061  67.010696  67.293900  53.583618  4872986
2016-09-06  16.964001  17.110001  13.092361  36132000  67.337952  67.646317  66.381371  66.714912  53.122574  5832742
2016-09-07  16.771000  16.889999  12.924018  31437000  66.532410  66.891129  66.261803  66.614220  53.042404  4010954
2016-09-08  16.656000  16.837999  12.884229  18680000  66.463181  66.809311  66.406548  66.551292  52.992298  4465408

Ticker             AMT                                                                  O                        \
Price             Open        High         Low       Close  Adj Close   Volume       Open       High        Low
Date
2016-09-01  113.699997  113.849998  112.839996  113.820000  87.284950  1157700  63.565891  64.050385  63.284885
2016-09-02  114.330002  115.529999  114.239998  115.089996  88.258888  1747300  63.953487  65.649223  63.934109
2016-09-06  115.599998  117.309998  115.209999  117.150002  89.838615  2391100  64.437981  65.096901  63.875969
2016-09-07  116.839996  117.150002  116.349998  116.830002  89.593208  1415900  65.164726  65.968994  65.096901
2016-09-08  116.309998  116.779999  116.230003  116.250000  89.148460  3568700  65.436050  65.765503  65.048447

Ticker                                          AMZN                                                             AAPL  \
Price           Close  Adj Close   Volume       Open       High        Low      Close  Adj Close    Volume       Open
Date
2016-09-01  63.701550  39.399670  1500425  38.544998  38.602001  38.337502  38.530998  38.530998  35846000  26.535000
2016-09-02  64.215118  39.717316  1229731  38.705502  38.799999  38.584999  38.622002  38.622002  43636000  26.924999
2016-09-06  65.096901  40.262684  1342632  38.702000  39.473999  38.511002  39.443501  39.443501  74396000  26.975000
2016-09-07  65.881783  40.748146  1499806  39.476501  39.539501  39.216499  39.223999  39.223999  48492000  26.957500
2016-09-08  65.329460  40.406536  2818908  39.194500  39.325001  39.071999  39.202999  39.202999  40610000  26.812500


In [15]:
#Reorganize the universe data into row long format

company_frame = []

for ticker in tickers:
    #handle any potential yfinance column arrangement differences
    if not isinstance(universe_data.columns, pd.MultiIndex):
        if ticker == tickers[0]:
            ticker_df = universe_data.copy()
        else:
            continue

    elif ticker in universe_data.columns.get_level_values(0):
        ticker_df = universe_data[ticker].copy()
        
    elif ticker in univer_data.columns.get_level_values(1):
        ticker_df = universe_data.xs( ticker, axis=1, level=1,).copy()

    else:
        print(f"No columns found for {ticker}")
        continue

    if ticker_df.empty or ticker_df.dropna(how="all").empty:
        print(f"No data available for {ticker}")
        continue 
        
   #Turn date index into normal column
    ticker_df = ticker_df.reset_index()
   #standardize date column name
    ticker_df = ticker_df.rename( columns={ "Date": "Date", "Datetime":"Date"})

    ticker_df["Ticker"] = ticker

    company_frame.append(ticker_df)

In [19]:
#Combine all companies 

universe_df = pd.concat(company_frame, ignore_index=True)

#Arrange columns and rows
universe_df["Date"] = pd.to_datetime(universe_df["Date"])
universe_df = universe_df.sort_values( ["Ticker", "Date"]).reset_index(drop=True)

print("Combined data shape:", universe_df.shape)
print("Companies:", universe_df["Ticker"].nunique())

display(universe_df.head(10))

Combined data shape: (125650, 8)
Companies: 50

Price       Date       Open       High        Low      Close  Adj Close     Volume Ticker
0     2016-09-01  26.535000  26.700001  26.405001  26.682501  24.407614  106806000   AAPL
1     2016-09-02  26.924999  27.000000  26.705000  26.932501  24.636307  107210000   AAPL
2     2016-09-06  26.975000  27.075001  26.877501  26.924999  24.629438  107521600   AAPL
3     2016-09-07  26.957500  27.190001  26.767500  27.090000  24.780375  169457200   AAPL
4     2016-09-08  26.812500  26.817499  26.309999  26.379999  24.130911  212008000   AAPL
5     2016-09-09  26.160000  26.430000  25.782499  25.782499  23.584356  186228000   AAPL
6     2016-09-12  25.662500  26.430000  25.632500  26.360001  24.112614  181171200   AAPL
7     2016-09-13  26.877501  27.197500  26.809999  26.987499  24.686613  248704800   AAPL
8     2016-09-14  27.182501  28.257500  27.150000  27.942499  25.560196  443554800   AAPL
9     2016-09-15  28.465000  28.932501  28.372499  28.892500  26.429197  359934400   AAPL

In [29]:
#Sanity checks

print("Start date:", universe_df["Date"].min())
print("End date:", universe_df["Date"].max())

print("Rows per company:")
display(universe_df.groupby("Ticker").size().to_frame("Row_Count"))

print("\nMissing values by column:")
display(universe_df.isna().sum().to_frame("Missing_Count"))

Start date: 2016-09-01 00:00:00
End date: 2026-09-01 00:00:00
Rows per company:

        Row_Count
Ticker
AAPL         2513
ABBV         2513
ADBE         2513
AMD          2513
AMT          2513
AMZN         2513
APD          2513
AVGO         2513
BAC          2513
BLK          2513
CAT          2513
COP          2513
COST         2513
CRM          2513
CSCO         2513
CVX          2513
DIS          2513
DUK          2513
GE           2513
GOOGL        2513
GS           2513
HD           2513
HON          2513
INTC         2513
JNJ          2513
JPM          2513
KO           2513
LIN          2513
LLY          2513
MCD          2513
META         2513
MSFT         2513
NEE          2513
NFLX         2513
NKE          2513
NVDA         2513
O            2513
ORCL         2513
PFE          2513
PG           2513
PLD          2513
RTX          2513
SHW          2513
SO           2513
TSLA         2513
UNH          2513
UPS          2513
V            2513
WMT          2513
XOM          2513

Missing values by column:

           Missing_Count
Price
Date                   0
Open                   0
High                   0
Low                    0
Close                  0
Adj Close              0
Volume                 0
Ticker                 0

In [31]:
#save file

universe_file = raw_data_dir / "universe_50.csv"

universe_df.to_csv(universe_file, index=False)

print("Saved to:", universe_file)
print("File exists?", universe_file.exists())

Saved to: /Users/nghitran/CapSTOKED/data/raw/universe_50.csv
File exists? True

In [45]:
#Download AMAZON subset to do preliminary works

amzn_data = yf.download( tickers="AMZN", start=START_DATE, end=END_DATE,
                       interval="1d", auto_adjust=False, actions=False,
                       progress=True, timeout=30)

#mitigating yfinance's potential multiindex columns
if isinstance(amzn_data.columns, pd.MultiIndex):
    
    if "AMZN" in amzn_data.columns.get_level_values(0):
        amzn_data = amzn_data["AMZN"].copy()
        
    elif "AMZN" in amzn_data.columns.get_level_values(1):
        amzn_data = amzn_data.xs("AMZN", axis=1, level=1).copy()
        

#Keep OHLCV, replace Close with adjusted close 
amzn_df = amzn_data[["Open", "High", "Low","Adj Close", "Volume"]].copy()
amzn_df = amzn_df.rename(columns={"Adj Close": "Adj_Close"})

amzn_df.index.name = "Date"
amzn_df = amzn_df.reset_index()

amzn_df = amzn_df[ ["Date", "Open", "High", "Low", "Adj_Close", "Volume"]]

amzn_df["Date"] = pd.to_datetime(amzn_df["Date"])

print("Amazon data shape:", amzn_df.shape)
display(amzn_df.head(10))

[*********************100%***********************]  1 of 1 completed

Amazon data shape: (2513, 6)

Price       Date       Open       High        Low  Adj_Close    Volume
0     2016-09-01  38.544998  38.602001  38.337502  38.530998  35846000
1     2016-09-02  38.705502  38.799999  38.584999  38.622002  43636000
2     2016-09-06  38.702000  39.473999  38.511002  39.443501  74396000
3     2016-09-07  39.476501  39.539501  39.216499  39.223999  48492000
4     2016-09-08  39.194500  39.325001  39.071999  39.202999  40610000
5     2016-09-09  38.967999  39.049999  38.005501  38.007000  85146000
6     2016-09-12  37.867500  38.632999  37.799999  38.574501  62494000
7     2016-09-13  38.438499  38.494499  37.952499  38.050499  62344000
8     2016-09-14  38.110001  38.375000  37.942501  38.054501  50460000
9     2016-09-15  38.099998  38.543499  37.879002  38.484501  60680000

In [47]:
#Sanity check

print("Date range", amzn_df["Date"].min(), "to", amzn_df["Date"].max())

print("\nMissing values:")
display(amzn_df.isna().sum().to_frame("Missing_Count"))

Date range 2016-09-01 00:00:00 to 2026-09-01 00:00:00

Missing values:

           Missing_Count
Price
Date                   0
Open                   0
High                   0
Low                    0
Adj_Close              0
Volume                 0

In [49]:
#Save file

amzn_file = raw_data_dir / "amzn.csv"

amzn_df.to_csv(amzn_file, index=False)

print("Saved to:", amzn_file)
print("File exists?", amzn_file.exists())

Saved to: /Users/nghitran/CapSTOKED/data/raw/amzn.csv
File exists? True